### ISSUE TITLE
Why are you missing `public` access modifier?

### ISSUE THREAD

**Issue by yawboakye** [orignMaster/JavaApps#1]
One lines [#5](https://github.com/orignMaster/JavaApps/blob/master/FigureInWords.java#L5), [#7](https://github.com/orignMaster/JavaApps/blob/master/FigureInWords.java#L7), and [#13](https://github.com/orignMaster/JavaApps/blob/master/FigureInWords.java#L13) you're missing any access modifier. I think it's appropriate to make those properties as `private`, but why do you not need them?

**Comment by orignMaster** [comment]
Why do i need those variables or why do i need the access modifiers?
